#!/usr/bin/env python3
"""Writes Scripts/data/jmdict-pos.tsv: a part of speech for every row the
dictionary ships, read from JMdict.

JMdict is not in the repository — 118 MB, and nothing else needs it. Fetch
jmdict-eng-*.json from github.com/scriptin/jmdict-simplified/releases and pass
its path. Only the rows the app uses are written out, so the table stays small
and the build does not need JMdict at all.

JMdict is © the Electronic Dictionary Research and Development Group,
CC BY-SA 4.0; the derived table carries the same licence.

Usage:  python3 Scripts/extract-jmdict.py path/to/jmdict-eng.json
"""
import collections
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SCRIPTS = ROOT / "Scripts"
OUTPUT = SCRIPTS / "data" / "jmdict-pos.tsv"

# JMdict's tags, reduced to the app's eight. The first sense decides: it is
# the word's main use, and a noun that also takes する (n, vs) is shown as the
# noun it is in a lyric. 「vt」「vi」 and a bare 「vs」 say how a word conjugates or
# what it takes, not what it is, and are skipped.
def part(tags):
    for tag in tags:
        if tag in ("vt", "vi", "vs", "vs-c"):
            continue
        if tag.startswith("adj-i"):
            return "い형용사"
        if tag == "adj-na":
            return "な형용사"
        if tag.startswith(("v1", "v2", "v4", "v5", "vk", "vz", "vs-", "vr", "vn")):
            return "동사"
        if tag.startswith("adv"):
            return "부사"
        if tag == "prt":
            return "조사"
        if tag in ("exp", "int"):
            return "표현"
        if tag.startswith("n") or tag in ("pn", "num"):
            return "명사"
        if tag in ("conj", "pref", "suf", "ctr", "cop") or tag.startswith("aux"):
            return "기타"
    return None


def hira(text):
    return "".join(chr(ord(c) - 0x60) if "ァ" <= c <= "ヶ" else c for c in text)


def rows_to_tag():
    rows = json.loads((SCRIPTS / "curated.json").read_text())
    seed = ROOT / "Modules" / "JustSensei" / "Resources" / "seed-dictionary.json"
    if seed.exists():
        rows += json.loads(seed.read_text())
    for path in sorted((SCRIPTS / "additions").glob("*.json")):
        rows += json.loads(path.read_text())
    return {(r["l"], r["r"]) for r in rows if r.get("l") and r.get("r")}


def main():
    words = json.loads(pathlib.Path(sys.argv[1]).read_text())["words"]
    by_text = collections.defaultdict(list)
    for word in words:
        for text in [k["text"] for k in word["kanji"]] or [k["text"] for k in word["kana"]]:
            by_text[text].append(word)

    lines = []
    for headword, reading in sorted(rows_to_tag()):
        candidates = by_text.get(headword, [])
        # The entry read the way this row reads it; a headword alone would give
        # 上手 じょうず the part of speech of うわて.
        matching = [w for w in candidates if any(hira(k["text"]) == hira(reading) for k in w["kana"])]
        chosen = (matching or (candidates if len(candidates) == 1 else []))[:1]
        if not chosen or not chosen[0]["sense"]:
            continue
        name = part(chosen[0]["sense"][0]["partOfSpeech"])
        if name:
            lines.append(f"{headword}\t{reading}\t{name}")

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(
        "# Parts of speech from JMdict (EDRDG, CC BY-SA 4.0), reduced to the app's eight.\n"
        "# Generated by Scripts/extract-jmdict.py. Columns: headword, reading, part of speech.\n"
        + "\n".join(lines) + "\n"
    )
    print(f"{len(lines)} rows -> {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
