import Foundation

// Generated from kanjidic/JMdict-style translation of the Korean grammar
// explanations. Keyed by Pattern.display. See Scripts and the i18n pipeline.
extension GrammarPatterns {
    /// English explanations, keyed by the pattern's display form.
    static let englishExplanations: [String: String] = [
        "〜だって": "\"even; even ~; but/still.\" Used to emphasize the preceding word or to give a reason.",
        "〜なんて": "\"things like ~; the idea that ~.\" Used to speak of something lightly or with a note of surprise.",
        "〜なんか": "\"~ and such; things like ~.\" A colloquial way to play down the preceding word or cite it as an example.",
        "〜など": "\"~ etc.; and the like.\" Lists examples or plays something down; the literary counterpart of 「なんか」.",
        "〜って": "\"~ that; quotation marker.\" Colloquially quotes speech or thought, or brings up a topic.",
        "〜なければならない": "Expresses the obligation that one must do something. In lyrics it is shortened to 「〜なきゃ」 or 「〜なくちゃ」.",
        "〜なくてもいい": "Means that one does not have to do something.",
        "〜てはいけない": "A prohibition meaning one must not do something. In lyrics it is shortened to 「〜ちゃだめ」.",
        "〜ずにはいられない": "An emotionally charged expression meaning one cannot help but do something.",
        "〜ないでください": "A request asking someone please not to do something.",
        "〜しょうがない": "Means \"it can't be helped\" or \"unbearable.\" Often used to emphasize emotion.",
        "〜てたまらない": "Expresses the intensity of an emotion: so much that one cannot stand it.",
        "〜てならない": "Means that one feels something so strongly and involuntarily that it is unbearable.",
        "〜っこない": "\"There's no way ~.\" A colloquial way of strongly denying something.",
        "〜ようがない": "Means there is no way to do something.",
        "〜ことはない": "An expression that reassures or dissuades, saying there is no need to do something.",
        "〜しかない": "Means one has no choice but to do something.",
        "〜わけにはいかない": "Means that, given the circumstances, one cannot do something.",
        "〜はずがない": "A strong denial meaning there is no way something could be so.",
        "〜にちがいない": "A conviction that something must surely be so.",
        "〜にすぎない": "An expression that plays something down as being nothing more than that.",
        "〜ではない": "A negation meaning \"is not ~.\" The formal form of 「じゃない」.",
        "〜じゃないか": "\"~, isn't it?; ~, right?\" A colloquial way to confirm or assert something strongly.",
        "〜たくない": "Means one does not want to do something.",
        "〜かもしれない": "A conjecture meaning something might be so.",
        "〜ことができる": "Expresses the ability or possibility of doing something.",
        "〜させられる": "Causative-passive. Means being made to do something (often reluctantly).",
        "〜させてください": "\"Please let me do ~.\" An expression asking permission to do something oneself.",
        "〜させてもらう": "A humble expression meaning one does something with the other person's permission.",
        "〜てほしい": "Means one wants someone else to do something.",
        "〜てみる": "\"Try doing ~.\" Means to do something as an attempt.",
        "〜てあげる": "\"Do ~ for someone.\" Means one does something for the benefit of another.",
        "〜てくれる": "\"Do ~ for me.\" Means someone does something for the speaker's benefit.",
        "〜てもらう": "\"Have someone do ~.\" Means the speaker receives the benefit of another's action.",
        "〜ていただく": "The humble form of 「〜てもらう」. Politely elevates the other person's action.",
        "〜てください": "\"Please do ~.\" A polite request or instruction.",
        "〜なさい": "\"Do ~ (please).\" A gentle command used by someone of higher status.",
        "〜てある": "Indicates that something has been done and its resulting state remains.",
        "〜てから": "\"After doing ~.\" Indicates that the next action follows that one.",
        "〜ておく": "Means to do something in advance for later. In lyrics it is shortened to 「〜とく」.",
        "〜てくる": "Indicates an action moving toward the speaker, or a gradual change coming about.",
        "〜ていく": "Indicates an action moving away, or a change continuing on into the future. In lyrics it is shortened to 「〜てく」 or 「〜てった」.",
        "〜てしまう": "Indicates an action's completion, or regret and disappointment about it. In lyrics it is shortened to 「〜ちゃう」 or 「〜じゃう」.",
        "〜に決まってる": "\"It's definitely ~.\" A strong conviction that something is obviously so.",
        "〜ている": "Indicates an action in progress or a continuing state. In lyrics it is shortened to 「〜てる」.",
        "〜させる": "Causative. \"Make/let someone do ~.\"",
        "〜られる": "Passive \"be ~ed,\" or potential \"can ~.\" Which one depends on context.",
        "〜ようにする": "Means to make an effort so that something happens, or to make a point of doing it.",
        "〜ようになる": "A change meaning one has come to be able to, or come to, do something.",
        "〜ようとする": "Expresses the will or attempt to do something.",
        "〜ようと思う": "Means one makes up one's mind to do something.",
        "〜ように": "\"So that ~,\" or \"like/as ~.\" Also used for comparison.",
        "〜ようだ": "A comparison or conjecture meaning \"it seems like ~\" or \"like ~.\"",
        "〜ために": "\"In order to ~,\" or \"because of ~.\" Expresses purpose or reason.",
        "〜ことにする": "Means one decides on one's own to do something.",
        "〜ことになる": "Means that, by circumstances, it has been decided that something will be so.",
        "〜ことがある": "Means one has done something before, or that it happens on occasion.",
        "〜たい": "Means the speaker wants to do something.",
        "〜たくなる": "Indicates that one comes to want to do something, one's heart moving that way.",
        "〜たがる": "Indicates that someone else wants to do something; the desire of a third person.",
        "〜つもり": "Means one intends to do something.",
        "〜ましょう": "\"Let's ~; shall we ~?\" A polite way to invite doing something together.",
        "〜ませんか": "\"Won't you ~?\" A polite way of inviting someone to do something.",
        "〜てもいい": "A permission or concession meaning it is all right to do something.",
        "〜べき": "Means one ought to do something.",
        "〜ばいい": "Advice or a solution meaning it will do if one does something.",
        "〜たらいい": "Means it would be good, or it will do, if one does something.",
        "〜ばよかった": "Regret meaning \"I wish I had done ~.\"",
        "〜といい": "A wish meaning \"I hope ~ turns out that way.\"",
        "〜ほうがいい": "\"It's better to ~.\" A piece of advice.",
        "〜ほうが": "\"the ~ side.\" Used when comparing two things and choosing one.",
        "〜かも": "A colloquial way of casually letting drop a conjecture that something might be so.",
        "〜だろう": "A conjecture or confirmation that something is probably so.",
        "〜そうだ": "Means something looks a certain way, or seems about to happen.",
        "〜みたい": "Means \"it seems like ~,\" or \"similar to ~.\"",
        "〜らしい": "Means \"I heard that ~,\" or \"typical of ~.\"",
        "〜はず": "A well-grounded expectation that something is naturally so.",
        "〜かな": "\"I wonder if ~.\" A light, murmured question or wish, as if to oneself.",
        "〜かしら": "\"I wonder if ~.\" The same as 「かな」 but with a slightly softer nuance.",
        "〜わけ": "Means the reason or circumstances behind something.",
        "〜ものだ": "Means that something is naturally so, or recalls that it used to often be so.",
        "〜かどうか": "Expresses the question of whether or not something is so.",
        "〜と思う": "\"I think that ~.\" States one's own judgment or opinion.",
        "〜気がする": "\"I have a feeling that ~.\" Expresses a faint impression.",
        "〜ことか": "\"How ~ it is!\" Emphasizes the degree of an emotion in an exclamatory way.",
        "〜によると": "\"According to ~.\" Used to cite the source of information one has heard.",
        "〜という": "\"called ~; ~ that.\" Gives a name or explains content.",
        "〜たら": "A supposition meaning \"if/when ~ happens.\"",
        "〜なら": "A supposition meaning \"if that's the case.\" Takes up a topic and sets it as a condition.",
        "〜ば": "The conditional form. Sets up a condition meaning \"if one does ~.\"",
        "〜ても": "Attached to the て-form of verbs and adjectives to express concession, \"even if ~.\" Often used with 「たとえ」.",
        "〜ながら": "Indicates doing two actions at the same time.",
        "〜けど": "A contrastive conjunction; what follows runs counter to what precedes.",
        "〜からには": "\"Now that ~.\" Means that, since something is the case, one naturally must act accordingly.",
        "〜から": "Indicates a reason: \"so; because.\"",
        "〜ので": "Indicates a reason. Softer than 「から」.",
        "〜のに": "A contrastive conjunction tinged with disappointment or dissatisfaction, meaning \"even though.\"",
        "〜おかげで": "\"Thanks to ~.\" Used to gratefully attribute a good result to a cause.",
        "〜せいで": "\"Because of ~ (blame).\" Used to attribute a bad result to a cause.",
        "〜くせに": "\"even though; despite being ~.\" A contrastive expression carrying a note of displeasure.",
        "〜ものの": "A contrastive conjunction meaning \"although it is so.\"",
        "〜うちに": "\"while ~; before ~ happens.\" Indicates the interval during which a state holds.",
        "〜とたん": "\"the moment ~.\" Indicates that something else happens right after.",
        "〜とき": "\"when ~.\" Indicates the time or occasion of something.",
        "〜まえに": "\"before ~.\" Indicates coming ahead of that action.",
        "〜あとで": "\"after ~.\" Indicates coming after that action.",
        "〜たびに": "\"every time ~.\" Means that each time something happens, it is so.",
        "〜ついでに": "\"while one is at it.\" Indicates doing something else on the same occasion.",
        "〜わりに": "\"considering ~; for ~.\" Indicates a degree different from what one would expect.",
        "〜だけ": "A limitation meaning \"only that.\"",
        "〜しか": "A limitation meaning \"nothing but that.\" Followed by a negative.",
        "〜さえ": "\"even ~.\" Cites an extreme example, or indicates that just that is enough.",
        "〜こそ": "\"~ is precisely the one.\" Emphatically states that it is that and nothing else.",
        "〜ばかり": "Indicates \"nothing but ~,\" or the moment just after having done something.",
        "〜ほど": "\"as much as ~; to the extent that ~.\" Compares or emphasizes degree.",
        "〜くらい": "\"about ~; as much as ~.\" Indicates an approximate degree.",
        "〜までに": "\"by ~.\" Indicates finishing something within that deadline.",
        "〜まで": "A range meaning \"until then; up to that extent.\"",
        "〜どころか": "\"far from ~; let alone ~.\" Emphasizes that, rather than the stated thing, the opposite is true.",
        "〜きり": "\"only ~; ~ and that's all.\" Indicates being limited to just that.",
        "〜だらけ": "\"covered in ~; full of ~.\" Means something is completely full of that.",
        "〜について": "\"about ~.\" Takes something as a topic or subject.",
        "〜によって": "\"by ~; depending on ~.\" Indicates a means, cause, or standard.",
        "〜に対して": "\"toward ~; with respect to ~.\" Indicates being directed at a partner or object.",
        "〜まま": "\"as it is; left ~.\" Means leaving a state unchanged.",
        "〜ずに": "\"without doing ~.\"",
        "〜がち": "\"tend to ~; apt to ~.\" Means such a tendency occurs often.",
        "〜つつ": "\"while ~.\" A literary way of doing two actions at once; also used for concession.",
        "〜っぱなし": "\"left ~.\" Indicates doing something and then leaving it that way, unattended.",
        "〜ことなく": "\"without ~ing.\" Indicates continuing on without doing something.",
        "〜んだ": "Adds a nuance of explanation or emphasis: \"it's that ~.\"",
        "〜もん": "\"because ~.\" A colloquial ending that gives a reason with a coaxing or pouting tone.",
        "〜じゃない": "\"~, isn't it?; ~, it's not.\" A colloquial form for confirming or lightly objecting.",
        "〜っぽい": "\"~-ish; ~-like.\" Means something has that feel to it.",
        "〜とか": "\"~ and such; like ~.\" Used to list examples lightly.",
        "〜たり": "\"doing ~ and ~, and so on.\" Lists several actions as examples.",
        "〜なくなる": "A change meaning something has ceased to be so.",
        "〜すぎる": "Means something is excessively so.",
        "〜ない": "A negation.",
    ]
}
